[workspace]
members = [
#    "contracts/cw20-wrapped",
    "contracts/cw721-base",
#    "contracts/cw721-wrapped",
#    "contracts/mock-bridge-integration",
#    "contracts/nft-bridge",
#    "contracts/token-bridge",
    "contracts/wormhole",
    "packages/cw721",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
